### PR TITLE
Add Gaia filters

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds the Gaia filter set to the built-ins. Pairs with https://github.com/sncosmo/sncosmo.github.io/pull/29.

### CODE REVIEW

**Comment by mcoughlin** [comment]
Thanks @benjaminrose. Could you retrigger the builtin test now that you merged that to see if the test passes? I cannot seem to.

**Comment by benjaminrose** [comment]
Reran the test. There were 8 failures, but none with the new Gaia filters. I'll trigger it again, hoping that this time the networks are working.

**Comment by benjaminrose** [comment]
All the tests passed! Looks good to me.

**Comment by mcoughlin** [comment]
Thanks @benjaminrose. @kboone, can I request another release that includes these? :)

**Comment by benjaminrose** [comment]
With ~6 months since the last release, this makes sense. v2.9.0 is on pypi now and will be on conda-forge in the next day or two.

**Pull request merged**
