### PR TITLE
Add 2MASS

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds the 2MASS filter set to the built-ins. Pairs with https://github.com/sncosmo/sncosmo.github.io/pull/26.

### CODE REVIEW

**Comment by kbarbary** [comment]
Needs updating after changes to https://github.com/sncosmo/sncosmo.github.io/pull/26

**Comment by mcoughlin** [comment]
@kbarbary updated.

**Review by kbarbary — APPROVED** [review]

**Comment by mcoughlin** [comment]
@kbarbary Any chance to have an intermediate release at somepoint to add in these built in features on pip install?

**Comment by kboone** [comment]
I made a new release (v2.8.0) with your changes. It should be pushed out to pip and conda shortly. Thanks for contributing!

**Pull request merged**
