### PR TITLE
Plot lc doc

### PR DESCRIPTION
**Pull request by rbiswas4**
Tried to modify the documentation for photometric data tables. Linking seems to still be a problem

### CODE REVIEW

**Comment by kbarbary** [comment]
You have the following forms:
```
 `~doc.photdata`  # in fitting.py
:doc:`~photdata`  # in fitting.py
:doc:`photdata`  # in plotting.py
```

I would expect only the last one to work. Does it?

By default, the backticks reference a code object. so `sncosmo.fit_lc` in backticks creates a link to the documentation on that object. The tilde `~` (e.g., `~sncosmo.fit_lc`) makes it so the link is still right, but only `fit_lc` is displayed in the docs: the module prefix is left off. Prepending `:doc:` in front of the backticks changes the "role": it tells markdown that you're referencing a rst document, rather than an object. That's why the first two forms above shouldn't work: photdata is an rst document, not an object in sncosmo itself.

**Comment by rbiswas4** [comment]
The last one was the one I started with. It did not work on my computer. I was trying different versions (without knowing the syntax logic) but did not find one that worked. I was wondering if it has something to do with my setup and whether things would be different on rtd. Hence the PR.

**Comment by kbarbary** [comment]
You seem to be right: the normal
```
:doc:`photodata`
```
doesn't work in docstrings. I just wrote "see the 'photometric data' section of the documentation" (no hyperlink).

**Comment by rbiswas4** [comment]
Ok ... I am deleting the branch with hanging commits.

**Pull request closed without merging**
