### PR TITLE
Small changes in fitting.py and models.py

### PR DESCRIPTION
**Pull request by srodney**
Added checkeffects to bandoverlap and propagating min chi2 parameter values into best-fit model objects.

bandoverlap_checkeffects_test_ipynb

### CODE REVIEW

**Comment by kbarbary** [comment]
Bug fix in `fitting.py` looks good. I think we never noticed this omission because the chisq function sets the model parameters as the minimization runs. So at the end of the minimization, the model parameters end up being pretty close to the optimal values. I guess you found cases where the model parameters were close (but not identical) to those reported in the result object?

The intent with `model.bandoverlap` was to always check effects (see #21) so I think the default behavior is just a bug. I'll take a closer look to make sure.

**Comment by kbarbary** [comment]
With `Model.bandflux` I think it would be sufficient to change `self._source.minwave() * (1. + z)` to `self.minwave()` and similarly for `maxwave()`.

**Comment by kbarbary** [comment]
I meant `Model.bandoverlap` not `Model.bandflux` in the previous comment (now edited).

**Comment by srodney** [comment]
"I guess you found cases where the model parameters were close (but not identical) to those reported in the result object?"

Yes... though I don't have a good test-case ready at hand.  

"With Model.bandoverlap I think it would be sufficient to change self._source.minwave() * (1. + z) to self.minwave() and similarly for maxwave()."

Yep.  I think you're right.  Fixed in the latest commit.

**Comment by kbarbary** [comment]
Looks good.

As a side note, instead of doing `git merge upstream/master` to merge the latest commits to master into your branch, you can do `git rebase upstream/master`. The two methods are pretty similar in that you will have to resolve any conflicts that git cannot automatically resolve. The difference is that `git rebase` "rewrites" your commits so it looks like you started from where `upstream/master` is. The benefit being that the history is more linear and there aren't a lot of extra merge commits.

**Pull request merged**
