### PR TITLE
Transition CI from Travis to Github Actions

### PR DESCRIPTION
**Pull request by ykwang1**
Environment setup is done using tox, rather than the scripts from .continuous integration. See .github/workflows/ci_tests.yml for matrix of tests. 

Still in progress
- oldestdeps environment not being set up properly
- coverage test not uploaded properly
- Need to check that testing via github actions behaves as expected (so far tests have been run using tox, e.g. tox -e env)

### CODE REVIEW

**Comment by ykwang1** [comment]
I guess Issue #293 should be linked to this PR as well... not sure how to do that

**Comment by ykwang1** [comment]
Sorry, its been awhile since I've commented on this PR. I've replicated the travis CI matrix using github actions (bumping some of the python version numbers). As of now, only two of the tests are failing, the coverage test (which seems to fail because I can't upload the completed coverage test results), and the test with the oldest dependencies. Here's a report from my branch: https://github.com/ykwang1/sncosmo/actions/runs/582681165

I'm still trying to figure out which dependencies are causing it to fail, but in the mean time, should the minimum dependencies be kept the same, or should they be updated?

**Comment by kboone** [comment]
Great job so far! For the oldest dependencies test, it looks like there is something wrong with the `extinction` package. Does it work if you require a newer version of `extinction`? I don't think that the current test suite tries to run old versions of everything, so there is a good chance that `sncosmo` just doesn't label its version compatibility properly.

Is the coverage test a permission issue? I'm not familiar with how this works, but I could dig into it if that would be helpful.

**Comment by bsipocz** [comment]
I will try to find some time this week to do a review here, I'm sorry to let it slip.

**Comment by benjaminrose** [comment]
From the discussion of #298, can we add a test to make sure that the docs compile without errors? Thanks.

**Comment by kbarbary** [comment]
> Does it work if you require a newer version of extinction? I don't think that the current test suite tries to run old versions of everything, so there is a good chance that sncosmo just doesn't label its version compatibility properly.

I tried to take a look at the version history and [commit history](https://github.com/kbarbary/extinction/commits/master) of the extinction package to see what the minimum version should be. I think there have been some minor API changes since v0.2.2, but more importantly, there have been build system changes from v0.4.0 -> v0.4.5 that make the install more robust when installing with pip. I haven't looked, but this could be the cause of problems setting up the environment. (with tox we're using pip whereas on travis we were using conda).

I think it would be OK to bump the required version of extinction to v0.4.5 in sncosmo's `setup.py`.

**Comment by kbarbary** [comment]
> edit: Sorry. I realized that this was a bad request. Making a new test is not the same as changing who/how the tests are run.
> 
> From the discussion of #298, can we add a test to make sure that the docs compile without errors? Thanks.

Just to be clear, this does include a docs build in the test matrix, right?

**Comment by ykwang1** [comment]
Yup, should be testing the docs already:
https://github.com/ykwang1/sncosmo/blob/b84932543856e3b0be57031096951b9745fac69c/.github/workflows/ci_tests.yml#L38
https://github.com/ykwang1/sncosmo/runs/1938539222?check_suite_focus=true

**Comment by benjaminrose** [comment]
> Yup, should be testing the docs already:
> https://github.com/ykwang1/sncosmo/blob/b84932543856e3b0be57031096951b9745fac69c/.github/workflows/ci_tests.yml#L38
> https://github.com/ykwang1/sncosmo/runs/1938539222?check_suite_focus=true

Great! I don't think was happening in the TravisCI test matrix, #298 & #295.

**Comment by kboone** [comment]
This was merged as part of #309. Thanks again @ykwang1!

**Pull request merged**
