### PR TITLE
TESS

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds TESS to builtin filters (relevant given its popularity and public data). Pairs with https://github.com/sncosmo/sncosmo.github.io/pull/32.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@benjaminrose

**Comment by mcoughlin** [comment]
@benjaminrose Anything I can do to help? I added you as a collaborator on my sncosmo.github.io branch as it looks like you want a different name for the TESS filter.

**Comment by benjaminrose** [comment]
There are a lot of failures, but they don't look like they have to do with the TESS filters, except for "Download all builtins." But that URL worked for me just now, so my guess is that `HTTP Error 502` is a internet issue and not a SNCosmo issue, especially since the URL worked just now.

**Comment by mcoughlin** [comment]
Thank you @benjaminrose. The last thing is to understand when the next release might be possible.

**Comment by benjaminrose** [comment]
We usually wait for a few new things per release. I especially want to do that with all the issues we have in our CI system. Is it possible for you to [use the GitHub](https://matiascodesal.com/blog/how-use-git-repository-pip-dependency/) version for now?

**Comment by mcoughlin** [comment]
@benjaminrose Of course, I just try to avoid such dependencies when I can. Thanks for getting this in.

**Comment by mcoughlin** [comment]
Thanks @benjaminrose!

**Pull request merged**
