### PR TITLE
adding bandpass for the Kepler spacecraft

### PR DESCRIPTION
**Pull request by mrtommyb**
adding the response function found at
http://keplergo.arc.nasa.gov/CalibrationResponse.shtml

### CODE REVIEW

**Comment by kbarbary** [comment]
Cool!

Note that this alone won't allow one to automatically load the bandpass via, e.g., `get_bandpass("kepler")`. That requires adding a bit of code to `sncosmo/_builtins/bandpasses.py`. You can add it to this PR or I can do it after merging if you'd like.

**Comment by mrtommyb** [comment]
if it is as simple as adding the code below then I can do this. Is there anything else?

```python
kepler_meta = {
    'filterset': 'kepler',
    'retrieved': '14 Jan 2015',
    'description': 'Bandpass for the Kepler spacecraft',
    'dataurl': 'http://keplergo.arc.nasa.gov/CalibrationResponse.shtml,}
registry.register_loader(Bandpass, 'kepler', load_bandpass,
                         args=['../data/bandpasses/kepler.dat'], meta=kepler_meta)
```

**Comment by kbarbary** [comment]
Yep, that's it!

**Comment by kbarbary** [comment]
Thanks! The test failure is just due to the PEP8 style checker which gets run automatically.

**Pull request merged**
