### PR TITLE
GOTO

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds GOTO as a builtin bandpass (important given they are publicly announcing candidates in their filter set).

### CODE REVIEW

**Comment by mcoughlin** [comment]
@benjaminrose

**Comment by mcoughlin** [comment]
Thanks for merging @benjaminrose. I hope this one is now good to go.

**Comment by benjaminrose** [comment]
Yeah, sorry for the delay. My one question: GOTO is not a common telescope/acronym, I wonder if we should use the full name for `'filterset': 'The Gravitational-wave Optical Transient Observer'`. Thoughts?

**Comment by mcoughlin** [comment]
@benjaminrose could do, although then shouldn't we have done that for atlas / panstarrs/ ztf and everything else?

**Comment by benjaminrose** [comment]
Yes, this matches what is done elsewhere, so is viable. But Atlas, panSTARRS and ZTF are all very common surveys. Let's leave it as is, and people can go to `svo2.cab.inta-csic.es/svo/theory/fps` and get the details about the filters.

Again, sorry for being a bit slow. I was traveling last week and the second PR slipped through the cracks.

**Comment by mcoughlin** [comment]
Thanks @benjaminrose!

**Pull request merged**
